### Stages
stages:
    - test

### Variables
variables:
    TEST_HARDHAT: "testHH"
    TEST_LINTER: "lint"

### Templates
.yarn-setup: &yarn-setup
    image: node:latest
    before_script:
        - yarn install --frozen-lockfile
        
### Jobs
test-contract:
    stage: test
    <<: *yarn-setup
    script:
        - yarn c
        - yarn $TEST_LINTER
        - yarn $TEST_HARDHAT

slither-check:
    stage: test
    image: node:latest
    before_script:
        - apt update
        - apt install -y python3-pip
        - pip3 install slither-analyzer
        - yarn install --frozen-lockfile
    script:
        - yarn slither
