global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "smart-contracts"
    static_configs:
      - targets: ["monitor-app:4000"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
