---
apiVersion: 2

notifiers:
  - name: Pagerduty 
    type: pagerduty
    uid: notifier1
    send_reminder: true
    frequency: 15m
    settings:
      autoResolve: true
    secure_settings:
      integrationKey: ${SC_PG_INT_KEY}

  - name: Slack
    type: slack
    uid: notifier2
    org_name: Main Org.
    send_reminder: true
    settings: 
      recipient: ${SC_SLACK_CHANNEL}
    secure_settings: 
      token: ${SC_SLACK_TOKEN}
      url: ${SC_SLACK_CHANNEL_WEBHOOK}
    

    
